# Matrix multiplication
Example of how to calculate the net input for a hidden layer employing the dot product. This example is based in a linear relationship between weights and features.

In [1]:
import numpy as np

Generate a dummy dataset of 7 observtions and 5 features

In [2]:
np.random.seed(0) 

data = np.random.randint(low = 0,
                         high = 5,
                         size = (7, 5)) 

data

array([[4, 0, 3, 3, 3],
       [1, 3, 2, 4, 0],
       [0, 4, 2, 1, 0],
       [1, 1, 0, 1, 4],
       [3, 0, 3, 0, 2],
       [3, 0, 1, 3, 3],
       [3, 0, 1, 1, 1]])

Create a matrix of weights for a hidden layer of 3 neurons

In [3]:
np.random.seed(0)

weights = np.random.randint(low = 0,
                            high = 5,
                            size = (3, 5))

weights

array([[4, 0, 3, 3, 3],
       [1, 3, 2, 4, 0],
       [0, 4, 2, 1, 0]])

### Dot product
Apply the dot product of weights to data. This geneates a 7 (features) x 3 (neurons of the hidden layer) where each value in the cells are the net input.
In other words, the data has been transformed into a 7 obsevations and 3 features that correspond to the net input to pass to the hidden layer.

In [4]:
data.dot(weights.T)

array([[43, 22,  9],
       [22, 30, 20],
       [ 9, 20, 21],
       [19,  8,  5],
       [27,  9,  6],
       [33, 17,  5],
       [21,  9,  3]])